version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["Dependency"]
    # Handle updates for crates from github.com/paritytech/substrate manually.
    ignore:
      - dependency-name: "substrate-*"
      - dependency-name: "sc-*"
      - dependency-name: "sp-*"
      - dependency-name: "frame-*"
      - dependency-name: "fork-tree"
      - dependency-name: "remote-externalities"
      - dependency-name: "pallet-*"
      - dependency-name: "beefy-*"
      - dependency-name: "try-runtime-*"
      - dependency-name: "test-runner"
      - dependency-name: "generate-bags"
      - dependency-name: "sub-tokens"
    schedule:
      interval: "daily"