name: ci-check-test

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache cargo registry and index
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo
      - name: Update OS
        run: sudo apt-get update -qq
      - name: Install dependencies
        run: sudo apt install -y cmake pkg-config libssl-dev git gcc build-essential clang libclang-dev
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          default: true
      - name: Cargo Update
        run: cargo update -p environmental
      - name: Check
        run: cargo check --manifest-path node/parachain/Cargo.toml
      - name: Run tests
        run: cargo test --manifest-path node/parachain/Cargo.toml
