name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run scripts
      run: ./scripts/init.sh
    - name: Cargo Update
      run: cargo update -p environmental
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
